### ISSUE TITLE
WDIO Testrunner - Allure reporter

### ISSUE THREAD

**Issue by facusantillo** [sskorol/mocha-allure2-example#10]
Based on the documentation [here](https://webdriver.io/docs/allure-reporter) the allure instance on the WDIO API for testrunner implementations using Mocha, is slightly different than the one provided here. 

Is there any way of implementing this as the main reporting tool on a WDIO using mocha as the testrunner?

**Comment by sskorol** [comment]
@facusantillo WDIO maintains their own Allure reporter implementation based on the outdated allure-commons package. To use an official allure-js implementation, WDIO reporter must be completely re-written unfortunately. There's no way to integrate the existing solution as WDIO uses a custom communication layer between modules. So new reporter should follow their protocol. Well, it's possible, but requires time.
