### ISSUE TITLE
Getting error on running script 'test' : 'multi' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by KapilSethi20** [sskorol/mocha-allure2-example#3]

**Comment by sskorol** [comment]
`multi` is from `mocha-multi` package. Please make sure you've executed `yarn` command to install all the dependencies before triggering tests.

**Comment by KapilSethi20** [comment]
Yes, I did install dependencies. Anyway, I removed 'mocha-multi' altogether and used mocha-allure2-reporter only and it solved my purpose. Thank you.
