### ISSUE TITLE
Cypress integration with allure2 and ts-test-decorator

### ISSUE THREAD

**Issue by cuongnguyen2190** [sskorol/mocha-allure2-example#6]
Hello,

I want to use ts-test-decorator apply for cypress test but I got this error:
`Error: Cannot find module './scripts/package-json-cullify' from 'C:\Users\fraser\code\node_modules\mocha'`

Is there any way to resolve issue or example for writing test in cypress using OOP style from ts-test-decorator and generating allure report after test ?

Thanks

**Comment by sskorol** [comment]
@smalldragonvt hey, this error doesn't seem to be related to ts-test-decorators, as this package depends on `allure-js-commons` only. From your log, it seems like something mocha-related. You may want to share a sample project, where this issue is reproduced.

**Comment by cuongnguyen2190** [comment]
hello,

Please find my sample repo as below:
https://github.com/smalldragonvt/cypress_allure

**Comment by sskorol** [comment]
@smalldragonvt sorry, haven't yet checked. Will try to find time in the next couple of days.

**Comment by sskorol** [comment]
@smalldragonvt please check https://github.com/allure-framework/allure-mocha/issues/52
It's already reported and seems like there's a cypress-allure plugin linked in the last message.

**Comment by cuongnguyen2190** [comment]
Thank you, I will take a look.
