### ISSUE TITLE
How use @data for DDA?

### ISSUE THREAD

**Issue by MASQA** [sskorol/mocha-allure2-example#8]
Hi, I haven`t  experience with typescript and decorators.
Could you advice,  how use decorator _data_ for dda?
For example if I want return no one object from testdata(), but array of objects that Test will been executed for each objects in array ?

**Comment by sskorol** [comment]
@MASQA 
```typescript
public static testData = (): User[] => {
	return [user1, user2]
}
```

**Comment by MASQA** [comment]
Sorry, it looks like I had mistake in function for created array of my objects and because of this I was catching error of heap during test execution and thinking that trouble in row `data(Authorization.testdata)`

**Comment by sskorol** [comment]
If you still encounter issues, please share a link to your sample project with minimal steps to reproduce.
